-- Oracle Express 21.0.3c
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Create new SCHEMA
CREATE USER YouApp IDENTIFIED BY Password01;

-- Grant all permissions
GRANT CREATE SESSION TO YouApp;
GRANT CREATE TABLE TO YouApp;
GRANT CREATE VIEW TO YouApp;
GRANT CREATE PROCEDURE TO YouApp;
GRANT CREATE TRIGGER TO YouApp;
GRANT CREATE SEQUENCE TO YouApp;
GRANT CREATE JOB TO YouApp;

ALTER USER YouApp quota unlimited on USERS;

-- Login with YouApp

CREATE TABLE oauth2_registration_type(
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_type VARCHAR2(32) NOT NULL UNIQUE
);

INSERT INTO oauth2_registration_type(registration_type) VALUES ('YOUAPP');
INSERT INTO oauth2_registration_type(registration_type) VALUES ('GOOGLE');
INSERT INTO oauth2_registration_type(registration_type) VALUES ('OTHER');

CREATE TABLE role(
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(32) NOT NULL UNIQUE
);

INSERT INTO ROLE(name) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE(name) VALUES ('ROLE_MAINTAINER');
INSERT INTO ROLE(name) VALUES ('ROLE_USER');


CREATE TABLE principal(
  id VARCHAR2(56) PRIMARY KEY,
  given_name VARCHAR2(32) NOT NULL,
  family_name VARCHAR2(32) NOT NULL,
  email VARCHAR2(48) NOT NULL UNIQUE,
  username VARCHAR2(32) NOT NULL UNIQUE,
  password VARCHAR2(512) NULL,
  birthday DATE NULL,
  photo VARCHAR2(256) NULL,
  registration_date DATE NULL,
  email_confirmed NUMBER(1) DEFAULT 0,
  registration_type_id INT NOT NULL,
  role_id INT NOT NULL,
  FOREIGN KEY(registration_type_id) REFERENCES oauth2_registration_type(id) ON DELETE CASCADE,
  FOREIGN KEY(role_id) REFERENCES role(id) ON DELETE CASCADE
);

INSERT INTO principal(
  id,
  given_name,
  family_name,
  email,
  username,
  password,
  birthday,
  email_confirmed,
  registration_type_id,
  role_id
) VALUES (
  '4fafcfa3-bf1c-4c5f-b5b8-51a10b389f5f',
  'Alejandro',
  'Alejo',
  'alejandroalejo715@gmail.com',
  'alejandro',
  'KdNiQ6GAvFdPEaPaerJ9f9l/kLPXkybvLSQOX+rXInEQFNBA+x0aj07C/yhfxbAhlv1EFS+MooI0O6YZlkHLkbFB0sjGf2Rocr5zY92dhGZdLmTEldvi92qfR40DZqWPkBFwVMdPD2GcZIJSEhFNcKrlj7DeCF3iG8VGF55ogW7qTZvrBJCjFZlMqoQSgnwZiyxwcNQfnPAO4NR+IhKXy28BBRd6dNy/31esyurdCwk22AipxLskoex/Yg7rXuzHEA6M9xuvub8nUfoSigL6SwRjsJ4w9x1kgzeR6W2iVWqCNeVctZObIIRk2A6ayURXcAhfYjHtceSdCf70VI65KQ==',
  TO_DATE('2000-07-14','yyyy/MM/dd'),1,1,1
);

INSERT INTO principal(
  id,
  given_name,
  family_name,
  email,
  username,
  password,
  birthday,
  email_confirmed,
  registration_type_id,
  role_id
) VALUES (
  '77503902-813b-42d2-afe2-66e475c9da6b',
  'Matias',
  'Gaitan',
  'matias25@gmail.com',
  'matias',
  'KdNiQ6GAvFdPEaPaerJ9f9l/kLPXkybvLSQOX+rXInEQFNBA+x0aj07C/yhfxbAhlv1EFS+MooI0O6YZlkHLkbFB0sjGf2Rocr5zY92dhGZdLmTEldvi92qfR40DZqWPkBFwVMdPD2GcZIJSEhFNcKrlj7DeCF3iG8VGF55ogW7qTZvrBJCjFZlMqoQSgnwZiyxwcNQfnPAO4NR+IhKXy28BBRd6dNy/31esyurdCwk22AipxLskoex/Yg7rXuzHEA6M9xuvub8nUfoSigL6SwRjsJ4w9x1kgzeR6W2iVWqCNeVctZObIIRk2A6ayURXcAhfYjHtceSdCf70VI65KQ==',
  TO_DATE('1999-11-15','yyyy/MM/dd'),1,1,3
);