-- Oracle Express 21.0.3c
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Create new SCHEMA
CREATE USER YouApp IDENTIFIED BY Password01;

-- Grant all permissions
GRANT CREATE SESSION TO YouApp;
GRANT CREATE TABLE TO YouApp;
GRANT CREATE VIEW TO YouApp;
GRANT CREATE PROCEDURE TO YouApp;
GRANT CREATE TRIGGER TO YouApp;
GRANT CREATE SEQUENCE TO YouApp;
GRANT CREATE JOB TO YouApp;

ALTER USER YouApp quota unlimited on USERS;

-- Login with YouApp

CREATE TABLE oauth2_registration_type(
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_type VARCHAR2(32) NOT NULL UNIQUE
);

INSERT INTO oauth2_registration_type(registration_type) VALUES ('YOUAPP');
INSERT INTO oauth2_registration_type(registration_type) VALUES ('GOOGLE');
INSERT INTO oauth2_registration_type(registration_type) VALUES ('OTHER');

CREATE TABLE role(
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(32) NOT NULL UNIQUE
);

INSERT INTO ROLE(name) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE(name) VALUES ('ROLE_MAINTAINER');
INSERT INTO ROLE(name) VALUES ('ROLE_USER');


CREATE TABLE principal(
  id VARCHAR2(56) PRIMARY KEY,
  given_name VARCHAR2(32) NOT NULL,
  family_name VARCHAR2(32) NOT NULL,
  email VARCHAR2(48) NOT NULL UNIQUE,
  username VARCHAR2(32) NOT NULL UNIQUE,
  password VARCHAR2(512) NULL,
  birthday DATE NULL,
  photo VARCHAR2(256) NULL,
  registration_date DATE NULL,
  email_confirmed NUMBER(1) DEFAULT 0,
  registration_type_id INT NOT NULL,
  role_id INT NOT NULL,
  FOREIGN KEY(registration_type_id) REFERENCES oauth2_registration_type(id) ON DELETE CASCADE,
  FOREIGN KEY(role_id) REFERENCES role(id) ON DELETE CASCADE
);

INSERT INTO principal(
  id,
  given_name,
  family_name,
  email,
  username,
  password,
  birthday,
  email_confirmed,
  registration_type_id,
  role_id
) VALUES (
  '4fafcfa3-bf1c-4c5f-b5b8-51a10b389f5f',
  'Alejandro',
  'Alejo',
  'alejandroalejo715@gmail.com',
  'alejandro',
  'KdNiQ6GAvFdPEaPaerJ9f9l/kLPXkybvLSQOX+rXInEQFNBA+x0aj07C/yhfxbAhlv1EFS+MooI0O6YZlkHLkbFB0sjGf2Rocr5zY92dhGZdLmTEldvi92qfR40DZqWPkBFwVMdPD2GcZIJSEhFNcKrlj7DeCF3iG8VGF55ogW7qTZvrBJCjFZlMqoQSgnwZiyxwcNQfnPAO4NR+IhKXy28BBRd6dNy/31esyurdCwk22AipxLskoex/Yg7rXuzHEA6M9xuvub8nUfoSigL6SwRjsJ4w9x1kgzeR6W2iVWqCNeVctZObIIRk2A6ayURXcAhfYjHtceSdCf70VI65KQ==',
  TO_DATE('2000-07-14','yyyy/MM/dd'),1,1,1
);

INSERT INTO principal(
  id,
  given_name,
  family_name,
  email,
  username,
  password,
  birthday,
  email_confirmed,
  registration_type_id,
  role_id
) VALUES (
  '77503902-813b-42d2-afe2-66e475c9da6b',
  'Matias',
  'Gaitan',
  'matias25@gmail.com',
  'matias',
  'KdNiQ6GAvFdPEaPaerJ9f9l/kLPXkybvLSQOX+rXInEQFNBA+x0aj07C/yhfxbAhlv1EFS+MooI0O6YZlkHLkbFB0sjGf2Rocr5zY92dhGZdLmTEldvi92qfR40DZqWPkBFwVMdPD2GcZIJSEhFNcKrlj7DeCF3iG8VGF55ogW7qTZvrBJCjFZlMqoQSgnwZiyxwcNQfnPAO4NR+IhKXy28BBRd6dNy/31esyurdCwk22AipxLskoex/Yg7rXuzHEA6M9xuvub8nUfoSigL6SwRjsJ4w9x1kgzeR6W2iVWqCNeVctZObIIRk2A6ayURXcAhfYjHtceSdCf70VI65KQ==',
  TO_DATE('1999-11-15','yyyy/MM/dd'),1,1,3
);

--- OAuth2 Tables

CREATE TABLE client_authentication_method(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method VARCHAR2(128) NOT NULL UNIQUE
);

INSERT INTO client_authentication_method(id,method) VALUES (1,'CLIENT_SECRET_BASIC');
INSERT INTO client_authentication_method(id,method) VALUES (2,'CLIENT_SECRET_POST');
INSERT INTO client_authentication_method(id,method) VALUES (3,'CLIENT_SECRET_JWT');
INSERT INTO client_authentication_method(id,method) VALUES (4,'PRIVATE_KEY_JWT');
INSERT INTO client_authentication_method(id,method) VALUES (5,'NONE');

CREATE TABLE client_grant_type(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_type VARCHAR2(128) NOT NULL UNIQUE
);

INSERT INTO client_grant_type(id,grant_type) VALUES (1,'AUTHORIZATION_CODE');
INSERT INTO client_grant_type(id,grant_type) VALUES (2,'REFRESH_TOKEN');
INSERT INTO client_grant_type(id,grant_type) VALUES (3,'CLIENT_CREDENTIALS');
INSERT INTO client_grant_type(id,grant_type) VALUES (4,'PASSWORD');
INSERT INTO client_grant_type(id,grant_type) VALUES (5,'JWT_BEARER');

CREATE TABLE client_redirect_uri(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uri VARCHAR2(256) NOT NULL UNIQUE
);

INSERT INTO client_redirect_uri(id,uri) VALUES (1,'https://oidcdebugger.com/debug');
INSERT INTO client_redirect_uri(id,uri) VALUES (2,'youapp://oauth');

CREATE TABLE client_scopes(
     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     scope VARCHAR2(256) NOT NULL UNIQUE
);

INSERT INTO client_scopes(id,scope) VALUES (1,'openid');
INSERT INTO client_scopes(id,scope) VALUES (2,'profile');
INSERT INTO client_scopes(id,scope) VALUES (3,'email');

CREATE TABLE registered_client (
    id VARCHAR2(255) PRIMARY KEY,
    client_id VARCHAR2(255) NOT NULL,
    client_issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_secret VARCHAR2(512) DEFAULT NULL,
    client_secret_expires_at timestamp DEFAULT NULL,
    client_name VARCHAR2(255) NOT NULL,
    redirect_uris VARCHAR2(1000) DEFAULT NULL,
    scopes VARCHAR2(1000) NOT NULL,
    client_settings VARCHAR2(2000) NOT NULL,
    token_settings VARCHAR2(2000) NOT NULL
);

INSERT INTO registered_client(id, client_id, client_secret, client_name,
                              redirect_uris, scopes, client_settings, token_settings)
VALUES ('d7bee65f-6f08-4991-a63c-c5c605d9c584', 'youapp',
        'MkiIbZDAX4Uye7q+/Wp9BBlbU4bvEQlNYDRCVeWhdWSgnaelp4rpjKWu0zICSWxEQ5k/RxEcOCxboqZUQIIDijU+xy6AhRsriZZKneGymfn2W1Kom1MYwxGRoCwXr10AcWMu5k3zrLeh436osqi/bbu5YZVF3ggBP3jOESJ4b2htXDsQ+olv9YDt41U7y7om94bb/xbOV4odv2Tb6j8UscvniD/NHNRIdm4m53Bs0Oh9qBh6i2vI238svYbdcKdjCmr8ZpsSo/rROBNQwn+aeU5XzRZz6h0Yr19E1nj1PJVlcQPzxKI2h2Trek1TbQyjQNHl2vDiEBlAxQuOw3GuQQ==',
        'youapp_frontend', 'https://oidcdebugger.com/debug', 'openid', ' ', ' ');

CREATE TABLE registered_client_authentication_methods(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registered_client_id VARCHAR2(255) NOT NULL,
    authentication_methods_id INT NOT NULL,
    FOREIGN KEY (registered_client_id) REFERENCES registered_client(id) ON DELETE CASCADE,
    FOREIGN KEY (authentication_methods_id) REFERENCES client_authentication_method(id) ON DELETE CASCADE
);

INSERT INTO registered_client_authentication_methods(registered_client_id, authentication_methods_id) VALUES ('d7bee65f-6f08-4991-a63c-c5c605d9c584',1);

CREATE TABLE registered_client_grant_type(
     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     registered_client_id VARCHAR2(255) NOT NULL,
     grant_types_id INT NOT NULL,
     FOREIGN KEY (registered_client_id) REFERENCES registered_client(id) ON DELETE CASCADE,
     FOREIGN KEY (grant_types_id) REFERENCES client_grant_type(id) ON DELETE CASCADE
);

INSERT INTO registered_client_grant_type(registered_client_id, grant_types_id) VALUES ('d7bee65f-6f08-4991-a63c-c5c605d9c584',1);

CREATE TABLE registered_client_redirect_uris(
     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     registered_client_id VARCHAR2(255) NOT NULL,
     redirect_uris_id INT NOT NULL,
     FOREIGN KEY (registered_client_id) REFERENCES registered_client(id) ON DELETE CASCADE,
     FOREIGN KEY (redirect_uris_id) REFERENCES client_redirect_uri(id) ON DELETE CASCADE
);

INSERT INTO registered_client_redirect_uris(registered_client_id, redirect_uris_id) VALUES ('d7bee65f-6f08-4991-a63c-c5c605d9c584',1);
INSERT INTO registered_client_redirect_uris(registered_client_id, redirect_uris_id) VALUES ('d7bee65f-6f08-4991-a63c-c5c605d9c584',2);

CREATE TABLE registered_client_scope(
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        registered_client_id VARCHAR2(255) NOT NULL,
        scopes_id INT NOT NULL,
        FOREIGN KEY (registered_client_id) REFERENCES registered_client(id) ON DELETE CASCADE,
        FOREIGN KEY (scopes_id) REFERENCES client_scopes(id) ON DELETE CASCADE
);

INSERT INTO registered_client_scope(registered_client_id, scopes_id) VALUES ('d7bee65f-6f08-4991-a63c-c5c605d9c584',1);
INSERT INTO registered_client_scope(registered_client_id, scopes_id) VALUES ('d7bee65f-6f08-4991-a63c-c5c605d9c584',2);

CREATE TABLE authorization (
   id VARCHAR2(255) NOT NULL,
   registeredClientId VARCHAR2(255) NOT NULL,
   principalName VARCHAR2(255) NOT NULL,
   authorizationGrantType VARCHAR2(255) NOT NULL,
   attributes VARCHAR2(4000) DEFAULT NULL,
   state VARCHAR2(500) DEFAULT NULL,
   authorizationCodeValue VARCHAR2(4000) DEFAULT NULL,
   authorizationCodeIssuedAt timestamp DEFAULT NULL,
   authorizationCodeExpiresAt timestamp DEFAULT NULL,
   authorizationCodeMetadata VARCHAR2(2000) DEFAULT NULL,
   accessTokenValue VARCHAR2(4000) DEFAULT NULL,
   accessTokenIssuedAt timestamp DEFAULT NULL,
   accessTokenExpiresAt timestamp DEFAULT NULL,
   accessTokenMetadata VARCHAR2(2000) DEFAULT NULL,
   accessTokenType VARCHAR2(255) DEFAULT NULL,
   accessTokenScopes VARCHAR2(1000) DEFAULT NULL,
   refreshTokenValue VARCHAR2(4000) DEFAULT NULL,
   refreshTokenIssuedAt timestamp DEFAULT NULL,
   refreshTokenExpiresAt timestamp DEFAULT NULL,
   refreshTokenMetadata VARCHAR2(2000) DEFAULT NULL,
   oidcIdTokenValue VARCHAR2(4000) DEFAULT NULL,
   oidcIdTokenIssuedAt timestamp DEFAULT NULL,
   oidcIdTokenExpiresAt timestamp DEFAULT NULL,
   oidcIdTokenMetadata VARCHAR2(2000) DEFAULT NULL,
   oidcIdTokenClaims VARCHAR2(2000) DEFAULT NULL,
   PRIMARY KEY (id)
);

CREATE TABLE authorizationConsent (
  registeredClientId VARCHAR2(255) NOT NULL,
  principalName VARCHAR2(255) NOT NULL,
  authorities VARCHAR2(1000) NOT NULL,
  PRIMARY KEY (registeredClientId, principalName)
);