server:
  port: 8082

app:
  auth:
    keys:
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsKrepc59kltQwwoOWNJYiUYkn0mbgajSRY7KaftTjrQTfMpxv4CsNtFRJH24rsrTNre2Zm7T1WyQw6z8rBiemptG6at1GBRvsVglnWVoknmtj/oBFDbCJx2+CYjSksgmoetyuBaO437iZWR5C5LygDU74F41pavBvpavfUgUb34zoa7l/fryX3TDcbrKu6utx6usTXs1CoskpVbv2WmDUt3SRSRqYS0dKnPpENC/3HoGfCws0g0/MmU37sALXtPpxQq34193L8nBaQ7Xg8LXMD5lEGW96rDK5kobLqWK/3+haGTVlRfzrKROWRf91DGyHVnVBKT3o9r5BaMLuyjleQIDAQAB
      private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwqt6lzn2SW1DDCg5Y0liJRiSfSZuBqNJFjspp+1OOtBN8ynG/gKw20VEkfbiuytM2t7ZmbtPVbJDDrPysGJ6am0bpq3UYFG+xWCWdZWiSea2P+gEUNsInHb4JiNKSyCah63K4Fo7jfuJlZHkLkvKANTvgXjWlq8G+lq99SBRvfjOhruX9+vJfdMNxusq7q63Hq6xNezUKiySlVu/ZaYNS3dJFJGphLR0qc+kQ0L/cegZ8LCzSDT8yZTfuwAte0+nFCrfjX3cvycFpDteDwtcwPmUQZb3qsMrmShsupYr/f6FoZNWVF/OspE5ZF/3UMbIdWdUEpPej2vkFowu7KOV5AgMBAAECggEABmLW04WIUn8Mh1BYvms0Gho3/q4JegFhQHRt6rDUD2eBANTMkdCT6RNd7ITC5Uadpe+0HzXIYIGhJgGdzJbDPPF5+b5h6DHs66s1COB+jDTryjWOTm3ATOutT+jrO7USeG3rYq4mEiEnC+U63uk77Nh/xpeBNvDjewE1bMDrRDBrJN1xIPj3d2OGNVtdvpS7uSgssEutc71Wg+DIbnfq32AQ4R6QLjlX3ZRFBd2dLbZQJ+qhd7fX6VuUNDRbTnrYt5/Gkh5/Jkf94uFVmg3qoaTurnRt8Q9IAotHdZ8fcOwhfMBTplN1joTjpzLTxKnlW7wkV5iexKbZyaDsw2onAQKBgQD0k11nX/+uXW9MOB8hyoeFDiOOB9SjIjeXVVceG7O52Dn1gHLHtx/WVRL0c3Lf6iISaRe4ssn6TXnDzfRdSgIVJhZztB59HT3iNB8z98Y2Mdk97LXnj4IGuzENsru6x/VqstRTnhafZs8z4jvm9A4D4JBAVE5sHRTBbX0HXle12QKBgQC463V65fDYH4X+2zUZAinaf9ZfRl4WWNeTqjMB6OW62+coZFzGIbp9vNV9aD08Ml8ZjCIHKE5wh5vb5DhV64XzCy3zXX9Mw6U/nMKh/e/Nq8ZEDu1IM3/p5qm/eUHE+TvupPFleVEXi0S2muaTM9DnApiDGln2se6xb99NRJ7IoQKBgQDc98N84Wv00m/68f2Wnw//s72F1idUWFbXgIAcMLUZpHUBDNMnA5ldITHl7+SKz1OHRLHs6oO3hIYN1ScBnhrxlp7UXJjrOx8tHyBN6H+JeVIoM5RJqQu2Hyv7j08zOvPNOdLB1WPlEpMD8lNin3+GGz7ZEBJmdYPKGqzKmn8uSQKBgG4s478Ilzm9dnGFG5q93j/v4MK9QzufTToOsvtVTuLJOG2pdlkaKWnXA4AHhkyCWoT3KCMJkcqcEXGvBR20CQfoxkT0lO8gtikzdgdcK+9ng+Zy2k8lV/X9V2/ciCIauOmT3rutz3HuqU7+9ZgIzFOHCWU7YxSHqQaQ+AOqecxhAoGARopylzAsyWk8/DCoGkbOMKsnpzJV0OF7qlHN5fWJ1tSsX5TioVX5Bke0l/c0W80W1AlU1ubUpZQTqHjDpxoApRBYYwAaXFZE+sJHZeO9iOfwEEJSndOUitQvGvNJcUCmpnnaecOZO8pgOLfWYOdnATMLgzxGC2SqBJfccgnkyPY=

logbook:
  format:
    style: http

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: INFO
    sv.com: TRACE
    org.zalando.logbook: TRACE